export const GET_INITIAL_VALUES = 'GET_INITIAL_VALUES';
export const AMOUNT_CHANGED = 'AMOUNT_CHANGED';
export const CURRENCY_CODE_CHANGED = 'CURRENCY_CODE_CHANGED';
export const CURRENCY_RATES_CHANGED = 'CURRENCY_RATES_CHANGED';
